### ISSUE TITLE
[Help] How to use Token authorization in header instead of API key

### ISSUE THREAD

**Issue by pmagnuson** [devmuaz/flutter_clean_architecture#10]
Thanks for the great articles and example code!

My system uses Token Authentication in which an user token is attend to the Http Request header.  How would you recommend migrating the example to place this in the header rather than using the APIKey?

Thank you,

**Comment by devmuaz** [comment]
Hi @pmagnuson,
You can use something called `Interceptor` and basically, what it does is intercepting any API call request and response which in your case want to add the token to each request.

### Code Sample
```dart
class TokenInterceptor extends Interceptor {
  final GetStorageService _getStorageService = GetStorageService();

  String? get _token => _getStorageService.token;

  @override
  void onRequest(RequestOptions options, RequestInterceptorHandler handler) {
    if (_token != null) {
      options.headers[HttpHeaders.authorizationHeader] = 'Bearer $_token';
    }

    handler.next(options);
  }
}
```

The above example shows a `TokenInterceptor` class that can put the token to every request's header made by the app (can be null if for instance the user hasn't logged in yet).

And the `GetStorageService` is a class I made to store my data in it, in your case it could be anything you prefer.

### Usage
You can then add the class (the interceptor class) to your `Dio` instance that you're using to make API call requests like this
```dart

final Dio dio = Dio();
dio.interceptors.add(TokenInterceptor());
```

And you can create and add interceptors as much as you need and add them to your `Dio` instance
```dart
final Dio dio = Dio();
dio.interceptors.addAll([
    TokenInterceptor(),

	// Another one that you might wanna need to add
    SomeOtherInterceptor(),
]);
```

Now, with that being done you don't need to worry about the token anymore.. so when the user logs in successfully just store the token in the `GetStorageService` class (or what ever you prefer), and when the user logs out clear that token so it can be `null` again (which indicate the user is logged out).

I hope I covered the most of it, If you got the idea and the code I provided helped you with your case then please make sure to close this issue or leave it opened if you have anything in mind.

Thank you!

**Comment by pmagnuson** [comment]
Thank you.
