### ISSUE TITLE
DioError

### ISSUE THREAD

**Issue by LennyLip** [devmuaz/flutter_clean_architecture#6]
[DioError](https://github.com/devmuaz/flutter_clean_architecture/blob/1f5a860508ea93ed739d95d94b3396cba57b08e6/lib/src/data/repositories/articles_repository_impl.dart#L33) does not work with the new version of Dio:

1) "request" renamed to requestOptions
2) DioErrorType.RESPONSE -> DioErrorType.response

It is no good idea to use DioError in DataState I think. HTTP 403/404/500 etc.. is not a Dio error in fact.

**Comment by devmuaz** [comment]
Hello @LennyLip, the project and the articles have been updated to the latest changes.
