### ISSUE TITLE
Some new useful packages

### ISSUE THREAD

**Issue by specOper99** [devmuaz/flutter_clean_architecture#9]
I am reading your medium articles and checking your code so I thought that you might be able to make the code cleaner by using `freezed` instead of the regular class generated with the VSCode extensions.
Which will need a few tweaks in order to implement it cause you are already using the build runner

**Comment by devmuaz** [comment]
Hi @specOper99 thank you for opening this issue, yes you could absolutely do that and make such changes if that what you prefer the most, but in our demonstration cases, i had to use this method to make things clearer and simpler.

But as I said, it's pretty much ok if you wanna use your own better method like `freezed`, `json_serializable`, or any other tool you prefer.

I'm gonna be closing this, but feel free to reopen it at any time 🙏🏼
